config/routes.rb
Rails.application.routes.draw do

  resources :categories, :only =>[:new, :update, :index, :create, :edit,:destroy]

  resources :users, :only => [:new, :create, :show] do
    resources :restaurants, :only =>[:new, :create,:edit, :update, :destroy]
    resources :reservations, :only => [:index, :show, :destroy]
  end

  resources :sessions, :only => [:new, :create, :destroy]

  resources :restaurants, :only =>[:index, :show] do
    resources :reservations
  end

  root "restaurants#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :restaurants
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :user, through: :reservations
  belongs_to :user
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :restaurants
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def ensure_logged_in
  unless current_user
    flash[:notice] = "Please log in"
    redirect_to new_session_path
  end
end

helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  def index
    @categories = Category.all
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.build
  end

  def create
    #binding.pry
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      p @reservation.restaurant
      redirect_to restaurant_path(@reservation.restaurant)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
    if params[:restaurant_id]
      @restaurant = Restaurant.find(params[:restaurant_id])
      @reservations = @restaurant.reservations.all
      @title = "Reservation List for restaurant #{@restaurant.name}"
    elsif params[:user_id]
      @user = User.find(params[:user_id])
      @reservations = @user.reservations.all
      @title = "Reservation List for user #{@user.email}"
    end
  end

private
def reservation_params
  params.require(:reservation).permit(:start_time,:seats,:restaurant_id)
end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @restaurant = @user.restaurants.build
    @categories = Category.all
    @cat_ids = []
  end

  def create
    if Restaurant.create(restaurant_params)
      redirect_to user_path(params[:user_id])
    else
      render :new
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @restaurant = Restaurant.find(params[:id])
    @categories = Category.all
    @cat_ids = @restaurant.categories.all.inject([]){|arr, element| arr << element.id}
  end

  def update
    @user = User.find(params[:user_id])
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :user_id, :category_ids =>[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Log in successed"
    else
      flash[:alert] = "Log in failed"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "Log out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, :only=>[:show]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user
      redirect_to user_path(@user), notice: "Logged in"
    else
      flash[:alert] = "Fail to create new user"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @restaurants = @user.restaurants.all
    p @restaurants
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,:is_restaurant_owner)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class= "actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
  <% @categories.each do |cat| %>
  <li>
    <%= cat.name %>
    <%= link_to("Edit", edit_category_path(cat)) %>
  </li>
  <% end %>
</ul>
<%= link_to("New Category", new_category_path) %>

app/views/categories/new.html.erb
<h1>Create new category</h1>
<%= render 'form'  %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<div>Current User: <%= current_user.email %></div>
  <%= link_to("Log out", session_path("current"), method: :delete) %>
<% else %>
  <%= link_to("Log in", new_session_path) %>
  <%= link_to("Sign up", new_user_path) %>
<% end %>


<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>
  <%= f.hidden_field :restaurant_id %>
  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :seats %>
    <%= f.number_field :seats %>
  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservation List</h1>
<div>
<%= @title  %>
<ul>
  <% @reservations.each do |resevation| %>
  <li>
    <%= resevation.start_time %>
    <%= resevation.seats  %>
    <%= resevation.user.email  %>
  </li>
  <% end %>
</ul>
</div>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= render 'form' %>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for([@user,@restaurant]) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <fieldset>
    <legend>Restaurant Categories</legend>
    <% @categories.each do |cat| %>
      <div>
        <%= check_box_tag("category_restaurant_ids_#{cat.id}", cat.id, (!@cat_ids.empty? && @cat_ids.include?(cat.id)), {:name=>"restaurant[category_ids][]"}) %>
        <%= label_tag "category_restaurant_ids_#{cat.id}",cat.name  %>
      </div>
    <% end %>
  </fieldset>
  <%= f.hidden_field :user_id %>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<p>This is restaurant index</p>
<div>
  <% @categories.each do |cat| %>
    <div>
      <p><%=cat.name %></p>
      <div>
        <% cat.restaurants.all.each do |restaurant| %>
          <div>
            <%= restaurant.name  %>
            <%= link_to("Show", restaurant_path(restaurant)) %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant</h1>
<%= render 'form'  %>

app/views/restaurants/show.html.erb
<p>Restaurant Show Page</p>
<%= @restaurant.name  %>
<%= link_to("Reservation List", restaurant_reservations_path(@restaurant)) %>
<%= link_to("Make Reservation", new_restaurant_reservation_path(@restaurant)) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<div class="field">
  <%=f.label :email %>
  <%=f.text_field :email %>
</div>
<div class="field">
  <%=f.label :password %>
  <%=f.password_field :password %>
</div>
<div class="field">
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
</div>
<div>
  <%= f.label :is_restaurant_owner %>
  <%= f.check_box :is_restaurant_owner, {}, true, false %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>User Page</h1>
<p>User Email: <%= @user.email %></p>
<% if @user.is_restaurant_owner %>
<%= link_to("Create Restaurant", new_user_restaurant_path(@user)) %>
<%= link_to("View Reservations", user_reservations_path(@user)) %>
<%= link_to("Reservation List",  user_reservations_path(@user)) %>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= restaurant.name  %>
    <%= link_to("Edit", edit_user_restaurant_path(@user,restaurant)) %>
  </li>
  <% end %>
</ul>
<p><%= link_to("Category List", categories_path) %></p>
<% end %>